export const STREAM_START_REQUEST = 'STREAM_START_REQUEST';
export const STREAM_START_SUCCESS = 'STREAM_START_SUCCESS';
export const STREAM_START_FAIL = 'STREAM_START_FAIL';
export const STREAM_START_RESET = 'STREAM_START_RESET';



export const STREAM_STOP_REQUEST = 'STREAM_STOP_REQUEST';
export const STREAM_STOP_SUCCESS = 'STREAM_STOP_SUCCESS';
export const STREAM_STOP_FAIL = 'STREAM_STOP_FAIL';
export const STREAM_STOP_RESET = 'STREAM_STOP_RESET';


