
const EVENTS = {
    connection: "connection",
    CLIENT: {
      CREATE_ROOM: "CREATE_ROOM",
      SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
      JOIN_ROOM: "JOIN_ROOM",
      CREAT_ROOM_STREAM: "CREAT_ROOM_STREAM",
      STOP_STREAM: "STOP_ROOM_STREAM",
      WAITING_STREAM: "WAITING_STREAM",
      READY_STREAM: "READY_STREAM",
      CHANGE_TIME_STREAM: "CHANGE_TIME_STREAM",
  
  
  
  
  
    },
    SERVER: {
      ROOMS: "ROOMS",
      JOINED_ROOM: "JOINED_ROOM",
      ROOM_MESSAGE: "ROOM_MESSAGE",
      ROOM_STREAM: "ROOM_STREAM",
      STOPED_STREAM: "STOPED_ROOM_STREAM",
      DONE_WAITING_STREAM: "DONE_WAITING_STREAM",
      DONE_READY_STREAM: "DONE_READY_STREAM",
      CHANGED_TIME_STREAM: "CHANGED_TIME_STREAM",
  
  
  
  
  
    },
  };
    export default EVENTS;
    